Pr
Doughnutik/Neural_Network pull request #1
Opened 2024-05-11 13:40 UTC by Doughnutik

2024-05-11 19:26 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

У тебя полный пиздец в нейросети творится. Посмотри комментарий про то, что должна делать нейросеть. Она у тебя делает все что угодно, но только не то что надо.

Добавь все файлы в проект. Добавь clang-format и clang-tidy.

2024-05-11 19:26 UTC, DimaTrushin commented on .gitignore
> +a.out
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/CMakeLists.txt
> +add_compile_options(
НЕ используй никогда компиляторозависимые флаги в системах сборки! Как я это соберу с любым другим компилятором, который не gcc и не clang? Оборачивай такие вещи в проверку на компилятор и только потом устанавливай флаги. Так оно хотя бы соберется на любом компиляторе, просто флаги надо будет дописать. А без этого у тебя система сборки упадет с непонятной внутренней ошибкой.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
1) Перенеси это наверх после выбора языка.
2) Добавь строчку
```cpp
set(CMAKE_CXX_STANDARD_REQUIRED True)
```
А то cmake разрешено откатиться на более низкий стандарт.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/CMakeLists.txt
> +set(SOURCE main.cpp)
Где блять этот файл? Откудая должен высрать main.cpp файл? ак я вообще соберу проект, в котором не хватает файлов?

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ActivationFunction.h
> +    using act_func = std::function<Vector(const Vector&, bool is_derivative)>;
Не использовать bool или int и прочие флаги со встроенными типами. Лучше делать enum class с хорошими названиями состояний, которые еще дополнительно не может конвертнуться во что-то лишнее. Например тут можно сделать
```cpp
enum class Operation {
  Function, Derivative
};
```
И тогда вызов будет
```cpp
act_func(x, Operation::Derivative);
```
Но с другой стороны не понятно зачем такие чудеса, если можно просто хранить две std::function. Одну для функции другую для производной. В случае если у тебя не покомпонентное отображение, у этих методов даже сигнатуры будут разные.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ActivationFunction.h
> +
Не пиши в global namespace, заведи пространство имен для проекта и все пиши в него.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    size_t size_ = 0;
Лишнее данное. У тебя std::vector уже хранит внутри себя размер. Убрать это зависимое данное.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    Vector(const std::vector<double>& vec);
1) Во-первых, плохо делать конструкторы от конкретного контейнера. Тут много разных причин, одна из них в том, что ты можешь сюда подставить контейнер, который может кастануться к вектору и в результате создастся временный вектор, а потом ты из этого вектора данные скопируешь в конструкторе и после этого временный объект разрушится. Например, такое произойдет, когда ты напишешь код
```cpp
Vector x{1, 2, 3};
```
Дело в том, что в c++ выражение {1, 2 ,3} имеет тип std::initializer_list<int>. И при вызове конструктора у тебя создастся вектор по этому инициализатору (причем как копия). Потом ты эту копию по ссылке передаешь в конструктор и оттуда данные опять копируются внутрь. И в результате у тебя каждый раз будет вызов аллокации и двойного копирования.
2) Вторая проблема заключается в том, что ты раскрываешь детали имплементации. То есть пользовательский код будет зависеть от этого конкретного контейнера.

В целом в приличном обществе принято делать так.
а) Создай конструктор от std::initializer_list<double>
б) Создай конструктор от std::vector<double>&& (то есть от rvalue reference).
В первом случае ты принимаешь список инициализации и нет никакой конвертации. Однако, проблема списка инициализации -- он всегда константный и из него нельзя своровать данные. Второй конструктор позволяет тебе принимать вектор, но только для того чтобы его данные своровать и не реаллоцировать.

Еще есть вариант сделать такой трюк
```cpp
template<class... Ts>
static Vector create(Ts... args) {
  std::vector<double> data;
  (data.emplace_back(std::move(args)),...);
  return Vector(std::move(data));
}
```
А конструктор от вектора делаешь приватным. И тогда этим можно пользоваться так
```cpp
Vector x = Vector::create(1, 2, 3, 4);
```
Благо в 17 плюсах это легко пишется.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +
убери в хедере лишние пробелы между методами. Читать невозможно. В cpp файлах они наоборот должны быть, чтобы отделять имплементации друг от друга.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    Vector(size_t size);
Плохой конструктор, для вектора нет смысла создавать его какого-то размера, есть смысл создавать его заполненным чемто. То есть разумно сделать функцию
```cpp
static Vector zero(size_t size) {
  return ...;
}
// тогда вот та строчка создаст вектор длины 4 заполненный нулями.
Vector zero_vector = Vector::zero(4);
```
Аналогично имеет смысл определять методы создающие случайные вектора заданной длины, но нет смысла создавать просто вектор какой-то длины.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    void Init(size_t size);
Это просто пиздец по всем фронтам.
1) Во-первых, для инициализации у класса используется конструктор! Если у тебя есть какой-то метод, который для инициализации вектора надо дополнительно взывать, то какого хуя у тебя делает конструктор? Почему конструктор делает объект в некорректном состоянии?
2) Во-вторых, если этот метод вспомогательный и используется для чего-то в конструкторе, то какого хуя он НЕ приватный? Почему пользователь вообще должен его звать?
3) В-третьих, если этот метод вспомогательный для инициализации объекта, то у него не верная сигнатура. Правильно делать метод "чистильщик", который принимает аргументы и возвращает внутренности нового объкта. Например
```cpp
static std::vector<double> vector_of_zeros(size_t size);
```
И уже этот метод вызывается в конструкторе посредством
```cpp
Vector(size_t size) : vec_(vector_of_zeros(size)) {}
```
И не надо звать нигде в теле конструктора дополнительные init-ы или что-то в том духе.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    void RandomFill();
Вектор -- это НЕ контейнер. Это объект. Потому вместо того, чтобы сначала создать какой-то вектор, а потом его заполнять какими-то значениями, ты сразу создай в одном методе случайный вектор. Для этого используй named constructor idiom через статические методы
```cpp
static Vector random(size_t size) {
  std::vector<double> vec(size);
  // код инициализации случайными данными
  return Vector(std::move(vec));
}
// и используешь так
Vector v = Vector::random(4);
```
НЕ создавай объекты-зомби которые недоинициализированы или недосозданы. Именно для этого и нужны конструкторы, чтобы не было вот такой поебени с инициализаторами.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    void operator += (const Vector& other);
Не верная сигнатура, ты должен вернуть Vector&

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    void operator += (const Vector& other);
Где clang-format? Добавь его. Настрой свою IDE так, чтобы форматирование применялось на сохранение файлов. Тогда тебе не надо будет мучиться с форматированием никогда.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    Vector operator + (const Vector& other) const;
Я предпочитаю делать бинарные операторы френдами, чтобы была возможность делать конвертацию по двум аргументам, кроме того, в этом случае еще есть возможмность делать всякие оптимизационные хаки, которые не возможно сделать с оператором класса.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    std::pair<int, double> FindMax();
Не используй std::pair, потому что пользователю не понятно, что значат first и second. Заведи struct с нужным именем и нужными названиями полей. И тогда пользователь сможет по нормальным названиям обращаться к элементам структуры. Напримр можно сделать что-то такое
```cpp
struct VectorLocator {
  size_t index;
  double value;
};
```
Просто сейчас я даже не уверен у тебя тут int это ошибка или нет. Это индекс или количество раз сколько встретился максимум. Не возможно читать код с std::pair.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    std::pair<int, double> FindMax();
Какого хуя этот метод НЕ константный?

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    Vector operator * (double value) const;
Вот такая штука тебе не позволит написать
```cpp
Vector v;
Vector w = 4 * v;
// тебе все время придется писать
Vector z = v * 4;
```
Потому лучше сделай
```cpp
friend Vector operator*(const Vector& vec, double value);
friend Vector operator*(double value, const Vector& vec);
```
И тогда у тебя будет возможность делать уможение с обеих сторон.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    size_t rows_ = 0, cols_ = 0;
Достаточно хранить только одно из этих чисел, другое восстанавливается по размеру вектора и первому из них.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +public:
Здесь применимы все замечания по конструкторам из замечаний вектора.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    void RandomFill();
убрать

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    size_t GetCols() const;
У таких методов можно Get не писать. Будет удобнее.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    std::vector<Vector> matrix_;
НИКОГДА НЕ делай вектор векторов. Создавай один сплошной вектор размера rows * cols и делай умную индексацию.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    const Vector& operator[](size_t ind) const;
Не перегружай операто [] для матриц и многомерных массивов, делай опертор operator()(size_t row, size_t col) (его константную и не константную версию) для доступа к элементам.
Если хочешь сделать оператор [] который делает вектор, то лучше возвращать объект, который является VectorView. То есть он ведет себя как вектор, но только при этом данные в себе не хранит. Это избавит тебя от чрезмерного копирования данных.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
> +    Matrix T() const;
1) Лучше напиши Transpose.
2) Бывает два типа методов: inplace и out of place. Так вот методы класса которые вызываются через точку я предпочитаю делать inplace, чтобы они меняли именно тот объект, на котором ты вызываешь, например
```cpp
Matrix x;
// следующая строчка меняет сам x
x.transpose();
```
А если надо возвращать новый объект, то я обычно делаю статические методы
```cpp
Matrix x;
Matrix y = Matrix::transpose(x);
```
И эта штука возвращает новую матрицу.
В целом можно делать как угодно, я тут делюсь своими соображениями. Главное быть консистентным и не мешать два стиля, как у тебя с randoFill сейчас происходит.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.h
Для такого маленького файла может это и не стоит делать. Но вообще лучше придерживаться методологии: один класс -- одна пара h/cpp. Понятно, что там могут быть вспомогательные классы, но основной класс должен быть один.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +std::mt19937 gen(43);
1) Во-первых, Если ты что-либо объявляешь в cpp файле, то в обязательном порядке заворачивай это в anonymous namespace. Иначе у тебя получится ад и израиль на уровне линковки.
2) Во-вторых, так как глобальные переменные между разными единицами трансляции создаются в неспецифицированном порядке, то ты НЕ можешь использовать все методы использующие эти глобальные данные ни в одном конструкторе глобального объекта.
3) Если тебе нужен класс для рандома, то создай под это выделенный класс. Например
```cpp
class Random {
public:
  double normal(double a = 0., double sigma = 1.) {
    std::normal_distribution<double> distribution(a, sigma);
    return distribution(generator_);
  }
private:
  std::mt19937 generator_ = 43;
};
```
И тогда ты можешь сделать этот объект статической переменной класса, или глобальным объектом или статической переменной метода и звать уже его. А еще лучше, чтобы этот рандом тогда уж умел тебе сразу матрицы возвращать и векторы заполненные нужным образом.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +    return {id, vec_[id]};
Конвертация size_t к int! Какого хуя у тебя компилятор с таким количеством включенных флагов не ругается? Не игнорируй warning-ги компилятора. Выхлоп от компилятора должен быть пустым. Все случайные warning-ги надо давить через pragma.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +}
Это максимально тупой способ инициализировать вектор. Любая инициализация должна происходить в списке инициализации конструктора с помощью конструктора твоего поля, либо с помощью метода, который возвращает нужным образом инициализированное поле. В данном случае есть нужный конструктор у вектора (ГУГЛИ на cppreference какие есть конструкторы у используемых тобой контейнеров и вообще объектов).
```cpp
Vector::Vector(size_t size) : vec_(size, 0) {}
```
Вот и все. Либо другой вариант
```cpp
Vector::Vector(size_t size) : vec_(create_vector_of_zeros(size)) {}
```
где create_vector_of_zeros -- это метод, который строит нужный тебе контейнер (но в данном случае такого делать не надо, потому что есть уже готовый конструктор.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +    }
Это максимально тупо, что мешало сделать
```cpp
vec_ = vec;
```
???
Кроме того, это можно было написать так
```cpp
Vector::Vector(const std::vector<double>& vec) : vec_(vec) {}
```
И все.
Но это тоже не очень хорошо, куда лучше было бы сделать
```cpp
Vector::Vector(std::vector<double>&& vec) : vec_(std::move(vec)) {}
```
И ты можешь украсть данные из этого объекта. Но я бы этот конструктор сделал приватным, а публичным сделал бы конструктор от std::initializer_list.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +}
Убрать и сделать как я написал в h файле. И добавь метод в класс Random описанный выше, который возвращает сразу случайный вектор нужного размера.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +}
тут должен быть return *this;

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +    return new_vec;
НЕ надо повторять имплементацию! Раз у тебя уже есть inplace метод, то сделай так
```cpp
Vector Vector::operator+(const Vector& other) const {
  Vector sum = *this;
  sum += other;
  return sum;
}
```
И здесь еще к тому же затригерится rvo для sum.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +    for (size_t i = 0 ; i < size_; ++i) {
используй vec_size() везде вместо лишнего данного.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/LinAlg.cpp
> +    matrix_.assign(rows, Vector(cols));
Не используй питонячий стиль. Инициализируй все в списке инициализации.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Layer.h
> +    Matrix a_, aT_;
НИКОГДА НЕ объявляй переменные в одной строке!
Что вообще означают эти имена переменных? Что за aT_?

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Layer.h
> +    friend Network;
Какого хрена Network является другом этого класса? Убрать. У них нет общих инвариантов. Ты просто не предоставил нужный интерфейс у Layer для работы с ним. УБрать вообще всех друзей, ни у одного класса, который ты пишешь нет общего инварианта ни с одним другим классом нигде ни в одной строчке кода.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Layer.h
> +    void Init(size_t rows, size_t cols, const ActivationFunction& func);
Какого хуя. У тебя должен быть конструктор, который принимает размеры слоя и функцию активации, а не какая-то тупая Init функция. Вся инициализация должна всегда быть только в конструкторе, Если что-то кроме конструктора делает инициализацию -- это всегда ошибка. У конструктора могут быть вспомогатльные методы, но ни всега приватные и не доступны пользователю снаружи.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Layer.cpp
> +    aT_ = a_.T();
Нахуя ты хранишь транспонированную матрицу тут? Это же лишние данные.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Layer.cpp
> +void Layer::Init(size_t rows, size_t cols, const ActivationFunction& func) {
1) Переделать в конструктор и все инициализации сделать в списке инициализации. Убрать лишнее данное aT_.
2) Я бы принимал фукнкцию активации by value и потом делал бы мув внутрь слоя как и любые sink аргументы.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Functions.h
> +    double operator()(double v, bool is_derivative = false);
Почему НЕ статические функции?
Зачем этот дурацкий флаг?

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Functions.cpp
> +    auto f{ [](double x) -> double {return 1 / (1 + exp(-x));}};
У тебя задваивание кода. Почему ты не используешь оператор() в дабловую версию тут?

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Functions.cpp
> +Vector Sigmoida::operator()(const Vector& vec, bool is_derivative = false) {
Из-за булевого флага у тебя код более ужасный и содержит лишний scope.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Functions.cpp
> +        }
Вместо проверки внутри на каждой итерации цикла, такую проверку уж лучш сделать снаружи. И вообще тут должен быть switch по enum class случаям, а не вот эта байда. Я бы избавился от проверки на производную в рантайме и просто сделал два статических метода - один для функции, второй для проиводной.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Functions.cpp
> +    const double alpha = 1e-2; // можно менять
Это плохо, что у тебя тут есть неявная зависимость. Либо сделай это данными хранимыми в классе, либо передавай явно как аргумент, и уже в конструкторе функции активации будешь заворачивать это в лямбду.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Functions.cpp
> +        return x;
Это что угодно, но не ReLu и не ее leaky версия. Это хрень каая-то.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Functions.cpp
> +double ReLU_func(double x, bool is_derivative = false) {
Спрячь этот метод в приватную часть класса. Ну или как минимум сделай его тут в anonymous namespace

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ActivationFunction.h
> +    double operator()(double v, bool is_derivative = false);
Какого хуя операторы НЕ константные?

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ActivationFunction.h
> +    ActivationFunction(const act_func& func);
Принимай std::function по значению и потом делай мув из его. Либо сделай две версии от константной ссылки и от rvalue ссылки.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ActivationFunction.cpp
> +    func_ = func;
Блять это должно быть в списке инициализации.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ConvertMnistDataToTxt.cpp
> +int ReadInt(std::ifstream& in) {
заверни все в anonymous namespace

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ConvertMnistDataToTxt.cpp
> +void WriteImages(std::ifstream& in, std::ofstream& out) {
Я не знаю что эта функция делает, но глядя на ее название и сигнатуру, я сомневаюсь, что она делает то, что говорит название. Она говорит "пишу изображение" при этом она нигде в своих аргументах НЕ приимает никакого изображения. Вместо этого есть два файловых потока. Переписать!

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ConvertMnistDataToTxt.cpp
> +    out.close();
Никогда НЕ закрывай файловые потоки явно. Их закрывают деструкторы. Кроме того, твой метод нигде неговорит пользователю, что он закрыват потоки. Пользователь метода удивится, что нельзя дважды записать этим методом в поток ничего.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ConvertMnistDataToTxt.cpp
> +        in.open(argv[i + 1]);
что мешало это вызвать в одной строчке
```cpp
std::ifstream in(argv[i + 1]);
```
?? Создавай объекты конструкторами сразу в том состоянии, что ты хочешь.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/ConvertMnistDataToTxt.cpp
> +int main(int argc, char* argv[]) {
Вообще функция main так не пишется. Начнем с того, что у тебя нигде не отключены исключения в проекте. А одна из задач main -- следить, чтобы исключения не утекали в операционную систему. В целом main НЕ должна делать никакую конкретную работу, она занимается оркестровкой на самом глобальном уровне, всю работу она делигирует другим методам и даже обработку исключений. Вот как может выглядеть файл main.cpp
```cpp
#include "NeuralNetwork.h"
#include "Except.h"

int main() {
  try {
    nn::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +    size_t num_layers_;
Какого хуя, у тебя и так векторзнает свой размер, ты же НЕ НА СИ пишешь.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +    double learning_rate_ = 0.5;
Это НЕ должно храниться в нейросети. Это данное, которое имеет смысл только во время обучения и может меняться. Убрать.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +    std::vector<Vector> neurons_values_, neurons_errors_;
Это что за хрень? Если это поправки для весов, то они НЕ должн храниться в твоей нейросети, они лишь имеют смысл во время обучения.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +    std::vector<int> num_neurons_;
А это еще что за хрень? Это я вообще не понимаю что значит и что тут делает.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +
Это что угодно, но только НЕ интерфейс нейросети. У тебя этот класс делает что угодно, но только НЕ то что должна делать нейросеть. Вот какой интерфейс должн быть
```cpp
class Network {
public:
  Network(...); // тут должен быть конструктор позволяющий удобно создавать нейросеть
  Vector predict(const Vector& x) const; // метод который вычисляет значение нейросети на аргументе
  void train(const Data& train_data, double learning_rate, LossFunction loss, int batch_size, int epoches, ...); // метод для обучения нейросети
private:
  ...
};
```
Вот это то, что должно быть в интерфейсе у нейросети. Конкретная сигнатура методов значения не имеет, ты можешь ее написать как тебе удобнее. НО, сеть должна уметь вычислять свои значения и она должна уметь обучаться (если ей скормили все нужные для этого данные). Все остальные методы в лучшем случае приватные или это методы других классов.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +void LoadData(const std::vector<double>& vec);
Что это за метод? Что за данные ты грузишь тут и куда? Это ты веса для сети считываешь откуда-то? Или это ты данные для обучения куда-то загоняешь? Это все не понятно, это раз. А во-вторых, этой хуйни тут быть не должно!

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +void PrintData();
Больше всего меня радуют методы которые ничего не принимают и ничего не возвращают. У тебя же есть операторы << и >> для вывода и ввода в потоки. Зачем тут делать отдельный метод для печати? Почему такая не консистентность?

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +int Propagate();
Что это за метод и что самое главное, что он возвращает?

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.h
> +void ReadData();
Я даже разбираться не хочу, что это говно делает.

2024-05-11 19:26 UTC, DimaTrushin commented on Neural_Network_HSE/Network.cpp
переписать все.

2024-05-12 15:54 UTC, Doughnutik commented on .gitignore
> +a.out
Сделал

2024-05-12 16:03 UTC, Doughnutik commented on Neural_Network_HSE/CMakeLists.txt
> +add_compile_options(
Сделал

2024-05-12 16:03 UTC, Doughnutik commented on Neural_Network_HSE/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Сделал

2024-05-12 16:17 UTC, Doughnutik commented on Neural_Network_HSE/Network.h
> +void PrintData();
Методы PrintData сохраняет веса сети в файл, чтобы их потом можно было снова загрузить
 Метод ReadData соответственно их читает из файла

2024-05-15 15:26 UTC, Doughnutik commented on Neural_Network_HSE/CMakeLists.txt
> +set(SOURCE main.cpp)
Исправил

2024-05-15 15:27 UTC, Doughnutik commented on Neural_Network_HSE/ActivationFunction.h
> +    using act_func = std::function<Vector(const Vector&, bool is_derivative)>;
Сделал std::function

2024-05-15 15:27 UTC, Doughnutik commented on Neural_Network_HSE/Network.h
> +void LoadData(const std::vector<double>& vec);
Добавил комментарии в методы

2024-05-15 15:27 UTC, Doughnutik commented on Neural_Network_HSE/Network.h
> +void PrintData();
Изменил методы. Добавил комментарии

2024-05-15 15:28 UTC, Doughnutik commented on Neural_Network_HSE/Network.h
> +int Propagate();
Метод возвращает предсказанную цифру сети

2024-05-15 15:31 UTC, Doughnutik commented
Исправил большую часть косяков

2024-05-15 15:31 UTC, closed without merging